package generators

const (
	// Names
	roleName              = "role-%d"
	roleAssignmentName    = "role-assignment-%d"
	workspaceName         = "workspace-%d"
	blockStorageName      = "disk-%d"
	imageName             = "image-%d"
	instanceName          = "instance-%d"
	networkName           = "network-%d"
	internetGatewayName   = "internet-gateway-%d"
	routeTableName        = "route-table-%d"
	subnetName            = "subnet-%d"
	publicIpName          = "public-ip-%d"
	nicName               = "nic-%d"
	securityGroupRuleName = "security-group-rule-%d"
	securityGroupName     = "security-group-%d"

	// Endpoint URLs
	urlProvidersPrefix  = "/providers/%s"
	urlTenantsPrefix    = urlProvidersPrefix + "/tenants/%s"
	urlWorkspacesPrefix = urlTenantsPrefix + "/workspaces/%s"
	urlNetworkPrefix    = urlWorkspacesPrefix + "/networks/%s"

	regionURL              = urlProvidersPrefix + "/regions/%s"
	regionListURL          = urlProvidersPrefix + "/regions"
	skuURL                 = urlTenantsPrefix + "/skus/%s"
	skuListURL             = urlTenantsPrefix + "/skus"
	roleURL                = urlTenantsPrefix + "/roles/%s"
	roleListURL            = urlTenantsPrefix + "/roles"
	roleAssignmentURL      = urlTenantsPrefix + "/role-assignments/%s"
	roleAssignmentListURL  = urlTenantsPrefix + "/role-assignments"
	workspaceURL           = urlTenantsPrefix + "/workspaces/%s"
	workspaceListURL       = urlTenantsPrefix + "/workspaces"
	blockStorageURL        = urlWorkspacesPrefix + "/block-storages/%s"
	blockStorageListURL    = urlWorkspacesPrefix + "/block-storages"
	imageURL               = urlTenantsPrefix + "/images/%s"
	imageListURL           = urlTenantsPrefix + "/images"
	instanceURL            = urlWorkspacesPrefix + "/instances/%s"
	instanceListURL        = urlWorkspacesPrefix + "/instances"
	instanceStartURL       = urlWorkspacesPrefix + "/instances/%s/start"
	instanceStopURL        = urlWorkspacesPrefix + "/instances/%s/stop"
	instanceRestartURL     = urlWorkspacesPrefix + "/instances/%s/restart"
	networkURL             = urlWorkspacesPrefix + "/networks/%s"
	networkListURL         = urlWorkspacesPrefix + "/networks"
	internetGatewayURL     = urlWorkspacesPrefix + "/internet-gateways/%s"
	internetGatewayListURL = urlWorkspacesPrefix + "/internet-gateways"
	nicURL                 = urlWorkspacesPrefix + "/nics/%s"
	nicListURL             = urlWorkspacesPrefix + "/nics"
	publicIpURL            = urlWorkspacesPrefix + "/public-ips/%s"
	publicIpListURL        = urlWorkspacesPrefix + "/public-ips"
	routeTableURL          = urlNetworkPrefix + "/route-tables/%s"
	routeTableListURL      = urlNetworkPrefix + "/route-tables"
	subnetURL              = urlNetworkPrefix + "/subnets/%s"
	subnetListURL          = urlNetworkPrefix + "/subnets"
	securityGroupRuleURL   = urlWorkspacesPrefix + "/security-group-rules/%s"
	securityGroupURL       = urlWorkspacesPrefix + "/security-groups/%s"
	securityGroupListURL   = urlWorkspacesPrefix + "/security-groups"

	// Resources
	resourceTenantsPrefix    = "%s/tenants/%s"
	resourceWorkspacesPrefix = resourceTenantsPrefix + "/workspaces/%s"
	resourceNetworkPrefix    = resourceWorkspacesPrefix + "/networks/%s"

	regionResource              = "%s/regions/%s"
	regionListResource          = "%s/regions"
	skuResource                 = resourceTenantsPrefix + "/skus/%s"
	skuListResource             = resourceTenantsPrefix + "/skus"
	roleResource                = resourceTenantsPrefix + "/roles/%s"
	roleListResource            = resourceTenantsPrefix + "/roles"
	roleAssignmentResource      = resourceTenantsPrefix + "/role-assignments/%s"
	roleAssignmentListResource  = resourceTenantsPrefix + "/role-assignments"
	workspaceResource           = resourceTenantsPrefix + "/workspaces/%s"
	workspaceListResource       = resourceTenantsPrefix + "/workspaces"
	blockStorageResource        = resourceWorkspacesPrefix + "/block-storages/%s"
	blockStorageListResource    = resourceWorkspacesPrefix + "/block-storages"
	imageResource               = resourceTenantsPrefix + "/images/%s"
	imageListResource           = resourceTenantsPrefix + "/images"
	instanceResource            = resourceWorkspacesPrefix + "/instances/%s"
	instanceListResource        = resourceWorkspacesPrefix + "/instances"
	networkResource             = resourceWorkspacesPrefix + "/networks/%s"
	networkListResource         = resourceWorkspacesPrefix + "/networks"
	internetGatewayResource     = resourceWorkspacesPrefix + "/internet-gateways/%s"
	internetGatewayListResource = resourceWorkspacesPrefix + "/internet-gateways"
	nicResource                 = resourceWorkspacesPrefix + "/nics/%s"
	nicListResource             = resourceWorkspacesPrefix + "/nics"
	publicIpResource            = resourceWorkspacesPrefix + "/public-ips/%s"
	publicIpListResource        = resourceWorkspacesPrefix + "/public-ips"
	routeTableResource          = resourceNetworkPrefix + "/route-tables/%s"
	routeTableListResource      = resourceNetworkPrefix + "/route-tables"
	subnetResource              = resourceNetworkPrefix + "/subnets/%s"
	subnetListResource          = resourceNetworkPrefix + "/subnets"
	securityGroupRuleResource   = resourceWorkspacesPrefix + "/security-group-rules/%s"
	securityGroupResource       = resourceWorkspacesPrefix + "/security-groups/%s"
	securityGroupListResource   = resourceWorkspacesPrefix + "/security-groups"

	// References
	regionRef            = "regions/%s"
	skuRef               = "skus/%s"
	workspaceRef         = "workspaces/%s"
	roleRef              = "roles/%s"
	roleAssignmentRef    = "role-assignments/%s"
	instanceRef          = "instances/%s"
	blockStorageRef      = "block-storages/%s"
	imageRef             = "images/%s"
	internetGatewayRef   = "internet-gateways/%s"
	nicRef               = "nics/%s"
	networkRef           = "networks/%s"
	routeTableRef        = networkRef + "/route-tables/%s"
	subnetRef            = networkRef + "/subnets/%s"
	publicIpRef          = "public-ips/%s"
	securityGroupRuleRef = "security-group-rules/%s"
	securityGroupRef     = "security-groups/%s"
)
