package generators

const (
	// Names
	roleName              = "role-%d"
	roleAssignmentName    = "role-assignment-%d"
	workspaceName         = "workspace-%d"
	blockStorageName      = "disk-%d"
	imageName             = "image-%d"
	instanceName          = "instance-%d"
	networkName           = "network-%d"
	internetGatewayName   = "internet-gateway-%d"
	routeTableName        = "route-table-%d"
	subnetName            = "subnet-%d"
	publicIpName          = "public-ip-%d"
	nicName               = "nic-%d"
	securityGroupRuleName = "security-group-rule-%d"
	securityGroupName     = "security-group-%d"

	// Endpoint URLs
	urlProvidersPrefix  = "/providers/%s"
	urlTenantsPrefix    = urlProvidersPrefix + "/tenants/%s"
	urlWorkspacesPrefix = urlTenantsPrefix + "/workspaces/%s"
	urlNetworkPrefix    = urlWorkspacesPrefix + "/networks/%s"

	regionURL                = urlProvidersPrefix + "/regions/%s"
	regionListURL            = urlProvidersPrefix + "/regions"
	skuURL                   = urlTenantsPrefix + "/skus/%s"
	skuListURL               = urlTenantsPrefix + "/skus"
	roleURL                  = urlTenantsPrefix + "/roles/%s"
	roleListURL              = urlTenantsPrefix + "/roles"
	roleAssignmentURL        = urlTenantsPrefix + "/role-assignments/%s"
	roleAssignmentListURL    = urlTenantsPrefix + "/role-assignments"
	workspaceURL             = urlTenantsPrefix + "/workspaces/%s"
	workspaceListURL         = urlTenantsPrefix + "/workspaces"
	blockStorageURL          = urlWorkspacesPrefix + "/block-storages/%s"
	blockStorageListURL      = urlWorkspacesPrefix + "/block-storages"
	imageURL                 = urlTenantsPrefix + "/images/%s"
	imageListURL             = urlTenantsPrefix + "/images"
	instanceURL              = urlWorkspacesPrefix + "/instances/%s"
	instanceListURL          = urlWorkspacesPrefix + "/instances"
	instanceStartURL         = urlWorkspacesPrefix + "/instances/%s/start"
	instanceStopURL          = urlWorkspacesPrefix + "/instances/%s/stop"
	instanceRestartURL       = urlWorkspacesPrefix + "/instances/%s/restart"
	networkURL               = urlWorkspacesPrefix + "/networks/%s"
	networkListURL           = urlWorkspacesPrefix + "/networks"
	internetGatewayURL       = urlWorkspacesPrefix + "/internet-gateways/%s"
	internetGatewayListURL   = urlWorkspacesPrefix + "/internet-gateways"
	nicURL                   = urlWorkspacesPrefix + "/nics/%s"
	nicListURL               = urlWorkspacesPrefix + "/nics"
	publicIpURL              = urlWorkspacesPrefix + "/public-ips/%s"
	publicIpListURL          = urlWorkspacesPrefix + "/public-ips"
	routeTableURL            = urlNetworkPrefix + "/route-tables/%s"
	routeTableListURL        = urlNetworkPrefix + "/route-tables"
	subnetURL                = urlNetworkPrefix + "/subnets/%s"
	subnetListURL            = urlNetworkPrefix + "/subnets"
	securityGroupRuleURL     = urlWorkspacesPrefix + "/security-group-rules/%s"
	securityGroupRuleListURL = urlWorkspacesPrefix + "/security-group-rules"
	securityGroupURL         = urlWorkspacesPrefix + "/security-groups/%s"
	securityGroupListURL     = urlWorkspacesPrefix + "/security-groups"

	// Resources
	resourceNetworkPrefix = "networks/%s"

	regionResource                = "regions/%s"
	regionListResource            = "regions"
	skuResource                   = "skus/%s"
	skuListResource               = "skus"
	roleResource                  = "roles/%s"
	roleListResource              = "roles"
	roleAssignmentResource        = "role-assignments/%s"
	roleAssignmentListResource    = "role-assignments"
	workspaceResource             = "workspaces/%s"
	workspaceListResource         = "workspaces"
	blockStorageResource          = "block-storages/%s"
	blockStorageListResource      = "block-storages"
	imageResource                 = "images/%s"
	imageListResource             = "images"
	instanceResource              = "instances/%s"
	instanceListResource          = "instances"
	networkResource               = "networks/%s"
	networkListResource           = "networks"
	internetGatewayResource       = "internet-gateways/%s"
	internetGatewayListResource   = "internet-gateways"
	nicResource                   = "nics/%s"
	nicListResource               = "nics"
	publicIpResource              = "public-ips/%s"
	publicIpListResource          = "public-ips"
	routeTableResource            = resourceNetworkPrefix + "/route-tables/%s"
	routeTableListResource        = resourceNetworkPrefix + "/route-tables"
	subnetResource                = resourceNetworkPrefix + "/subnets/%s"
	subnetListResource            = resourceNetworkPrefix + "/subnets"
	securityGroupRuleResource     = "security-group-rules/%s"
	securityGroupRuleListResource = "security-group-rules"
	securityGroupResource         = "security-groups/%s"
	securityGroupListResource     = "security-groups"

	// References
	refTenantsPrefix    = "%s/tenants/%s"
	refWorkspacesPrefix = refTenantsPrefix + "/workspaces/%s"
	refNetworkPrefix    = refWorkspacesPrefix + "/networks/%s"

	regionRef            = "%s/regions/%s"
	skuRef               = refTenantsPrefix + "/skus/%s"
	roleRef              = refTenantsPrefix + "/roles/%s"
	roleAssignmentRef    = refTenantsPrefix + "/role-assignments/%s"
	workspaceRef         = refTenantsPrefix + "/workspaces/%s"
	blockStorageRef      = refWorkspacesPrefix + "/block-storages/%s"
	imageRef             = refTenantsPrefix + "/images/%s"
	instanceRef          = refWorkspacesPrefix + "/instances/%s"
	networkRef           = refWorkspacesPrefix + "/networks/%s"
	internetGatewayRef   = refWorkspacesPrefix + "/internet-gateways/%s"
	nicRef               = refWorkspacesPrefix + "/nics/%s"
	publicIpRef          = refWorkspacesPrefix + "/public-ips/%s"
	routeTableRef        = refNetworkPrefix + "/route-tables/%s"
	subnetRef            = refNetworkPrefix + "/subnets/%s"
	securityGroupRuleRef = refWorkspacesPrefix + "/security-group-rules/%s"
	securityGroupRef     = refWorkspacesPrefix + "/security-groups/%s"
)
