on:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.md"
      - "docs/**"
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "*.md"
      - "docs/**"

name: Analyse

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
